---
title: "HW4 updated"
author: "Kat Lopez"
date: "11/25/2017"
output: html_document
---
```{r setup, include=FALSE}
PDS_stats= read.csv("~/Dropbox/3rd Fall/Longitudinal data analysis/STATS_resting_state_BRIEF.csv")
#this converts variables to numeric starting from column 4
id <- c(1,4:ncol(PDS_stats))
PDS_stats[,id] <- as.numeric(as.character(unlist(PDS_stats[,id])))
library(lavaan)
library(semTools)
library(semPlot)
library(lme4)
library(tidyr)
library(ggplot2)

#convert variables
PDS_stats$T3gecrs_combined_conv=PDS_stats$T3gecrs_Combined/100
PDS_stats$T12gecrs_conv=PDS_stats$T12gecrs/100
PDS_stats$T14gecrs_conv=PDS_stats$T14gecrs/100
```


10) Test measurement invariance across time for your construct. Can you run growth models? If there is evidence of non-invariance, what seems to be the problem?

```{r setup, include=FALSE}
#Baseline
config <- '
## define latent variables
  MIT3 =~ NA*T3initirs + L1*T3initirs + L2*T3wrkmrs + L3*T3plorgrs + L4*T3orgmars + L5*T3monirs
  MIT12 =~ NA*T12initirs + L1*T12initirs + L2*T12wrkmrs + L3*T12plorgrs + L4*T12orgmars + L5*T12monirs
  MIT14=~ NA*T14initirs + L1*T14initirs + L2*T14wrkmrs + L3*T14plorgrs + L4*T14orgmars + L5*T14monirs


## correlated residuals across time
  T3initirs ~~ T3wrkmrs + T3plorgrs + T3orgmars + T3monirs
  T3wrkmrs ~~ T3plorgrs + T3orgmars + T3monirs
  T3plorgrs  ~~ T3orgmars + T3monirs
  T3orgmars  ~~ T3monirs

  T12initirs ~~ T12wrkmrs + T12plorgrs + T12orgmars + T12monirs
  T12wrkmrs ~~ T12plorgrs + T12orgmars + T12monirs
  T12plorgrs  ~~ T12orgmars + T12monirs
  T12orgmars  ~~ T12monirs

  T14initirs ~~ T14wrkmrs + T14plorgrs + T14orgmars + T14monirs
  T14wrkmrs ~~ T14plorgrs + T14orgmars + T14monirs
  T14plorgrs  ~~ T14orgmars + T14monirs
  T14orgmars  ~~ T14monirs
'
config <- cfa(config, data=PDS_stats, meanstructure=TRUE, std.lv=TRUE, missing="ML")
summary(config, standardized=TRUE, fit.measures=TRUE)

#Weak constrain loading
weak <- '
## define latent variables
  MIT3 =~  L1*T3initirs + L2*T3wrkmrs + L3*T3plorgrs + L4*T3orgmars + L5*T3monirs
  MIT12 =~ L1*T12initirs + L2*T12wrkmrs + L3*T12plorgrs + L4*T12orgmars + L5*T12monirs
  MIT14=~  L1*T14initirs + L2*T14wrkmrs + L3*T14plorgrs + L4*T14orgmars + L5*T14monirs

## free latent variances at later times (only set the scale once)
  MIT12 ~~ NA*MIT12
  MIT14 ~~ NA*MIT14

## correlated residuals across time
  T3initirs ~~ T3wrkmrs + T3plorgrs + T3orgmars + T3monirs
  T3wrkmrs ~~ T3plorgrs + T3orgmars + T3monirs
  T3plorgrs  ~~ T3orgmars + T3monirs
  T3orgmars  ~~ T3monirs

  T12initirs ~~ T12wrkmrs + T12plorgrs + T12orgmars + T12monirs
  T12wrkmrs ~~ T12plorgrs + T12orgmars + T12monirs
  T12plorgrs  ~~ T12orgmars + T12monirs
  T12orgmars  ~~ T12monirs

  T14initirs ~~ T14wrkmrs + T14plorgrs + T14orgmars + T14monirs
  T14wrkmrs ~~ T14plorgrs + T14orgmars + T14monirs
  T14plorgrs  ~~ T14orgmars + T14monirs
  T14orgmars  ~~ T14monirs
'
weak <- cfa(weak, data=PDS_stats, meanstructure=TRUE, std.lv=TRUE, missing="ML")
summary(weak, standardized=TRUE, fit.measures=TRUE)

# strong constrain loadings and intercepts 
strong <- '
## define latent variables
  MIT3 =~  L1*T3initirs + L2*T3wrkmrs + L3*T3plorgrs + L4*T3orgmars + L5*T3monirs
  MIT12 =~ L1*T12initirs + L2*T12wrkmrs + L3*T12plorgrs + L4*T12orgmars + L5*T12monirs
  MIT14 =~  L1*T14initirs + L2*T14wrkmrs + L3*T14plorgrs + L4*T14orgmars + L5*T14monirs

## free latent variances at later times (only set the scale once)
  MIT12 ~~ NA*MIT12
  MIT14 ~~ NA*MIT14

## correlated residuals across time
  T3initirs ~~ T3wrkmrs + T3plorgrs + T3orgmars + T3monirs
  T3wrkmrs ~~ T3plorgrs + T3orgmars + T3monirs
  T3plorgrs  ~~ T3orgmars + T3monirs
  T3orgmars  ~~ T3monirs

  T12initirs ~~ T12wrkmrs + T12plorgrs + T12orgmars + T12monirs
  T12wrkmrs ~~ T12plorgrs + T12orgmars + T12monirs
  T12plorgrs  ~~ T12orgmars + T12monirs
  T12orgmars  ~~ T12monirs

  T14initirs ~~ T14wrkmrs + T14plorgrs + T14orgmars + T14monirs
  T14wrkmrs ~~ T14plorgrs + T14orgmars + T14monirs
  T14plorgrs  ~~ T14orgmars + T14monirs
  T14orgmars  ~~ T14monirs

## constrain intercepts across time
  T3initirs ~ t1*1
  T3wrkmrs ~ t2*1
  T3plorgrs ~ t3*1
  T3orgmars ~ t4*1
  T3monirs ~ t5*1
  
  T12initirs ~ t1*1
  T12wrkmrs ~ t2*1
  T12plorgrs ~ t3*1
  T12orgmars ~ t4*1
  T12monirs ~ t5*1
  
  T14initirs ~ t1*1
  T14wrkmrs ~ t2*1
  T14plorgrs ~ t3*1
  T14orgmars ~ t4*1
  T14monirs ~ t5*1

## free latent means at later times (only set the scale once)
  MIT12 ~ NA*1
  MIT14 ~ NA*1'

strong <- cfa(strong, data=PDS_stats, meanstructure=TRUE, std.lv=TRUE, missing="ML")
summary(strong, standardized=TRUE, fit.measures=TRUE)

#Comparing models
anova(config, weak) #no difference between model 
fitmeasures(weak)['cfi'] # 0.8395141

anova(weak, strong) #significant difference between model, strong model is preferred. 
fitmeasures(strong)['cfi'] # 0.8235042
d= 0.8395141-0.8235042 # slightly greater than .01 suggesting possible misfit. 


```

11) Fit a second order growth model. Compare and contrast the estimates with the normal latent growth model.
```{r setup, include=FALSE}
# Second Order Growth Model (repeated measures are latent variables)
# Metacognition Index of Brief: initiate, working memory, plan/organize, organization of material, & monitor [interpreted as the ability to self-manage tasks and monitor performance]

## Univariate Growth models
# First wave (T3)
  metacognition.index.T3= ' metacognition.index.T3 =~ T3initirs + T3wrkmrs + T3plorgrs +T3orgmars + T3monirs' 
  fit= cfa(metacognition.index.T3, data= PDS_stats, missing= "ML")
  summary(fit, fit.measures=TRUE, standardized=TRUE) 
  # RMSEA= 0.133 ; SRMR=0.026 
  # CFI= 0.977 ; TLI= 0.955
  
# Second wave (T12)
  metacognition.index.T12= ' metacognition.index.T12 =~ T12initirs + T12wrkmrs + T12plorgrs +T12orgmars + T12monirs' 
  fit2= cfa(metacognition.index.T12, data= PDS_stats, missing= "ML")
  summary(fit2, fit.measures=TRUE, standardized=TRUE)
  # RMSEA= 0.058; SRMR=0.016
  # CFI= 0.996 ; TLI= 0.991
  
# Third wave (T14)
  metacognition.index.T14= ' metacognition.index.T14 =~ T14initirs + T14wrkmrs + T14plorgrs +T14orgmars + T14monirs'
  fit3= cfa(metacognition.index.T14, data= PDS_stats, missing= "ML")
  summary(fit3, fit.measures=TRUE, standardized=TRUE)
  # RMSEA= 0.113 ; SRMR=0.022 
  # CFI= 0.983; TLI= 0.967
  
# Overall fit statistics at each individual wave appears to suggest acceptable fits
  
sec.order <- '
# define latent variables; MI for each waves 1,2,3; NA says no to default[done for the first indicator] and L1 to label each indicator
  
  MIT3 =~ NA*T3initirs + L1*T3initirs + L2*T3wrkmrs + L3*T3plorgrs + L4*T3orgmars + L5*T3monirs
  MIT12 =~ NA*T12initirs + L1*T12initirs + L2*T12wrkmrs + L3*T12plorgrs + L4*T12orgmars + L5*T12monirs
  MIT14=~ NA*T14initirs + L1*T14initirs + L2*T14wrkmrs + L3*T14plorgrs + L4*T14orgmars + L5*T14monirs

  
# intercepts[means] of indicators; fixing (constraining) the means of indicator to be same via t1 labels (making items the same across time); differences in mean gets pushed up to latent variable (MIT1, MIT12, MIT14) in the slope(?) 
 
  T3initirs ~ t1*1
  T3wrkmrs ~ t2*1
  T3plorgrs ~ t3*1
  T3orgmars ~ t4*1
  T3monirs ~ t5*1

  T12initirs ~ t1*1
  T12wrkmrs ~ t2*1
  T12plorgrs ~ t3*1
  T12orgmars ~ t4*1
  T12monirs ~ t5*1

  T14initirs ~ t1*1
  T14wrkmrs ~ t2*1
  T14plorgrs ~ t3*1
  T14orgmars ~ t4*1
  T14monirs ~ t5*1

# correlated residuals across time (item1 at t1 to item 1 at T2)
  T3initirs ~~ T3wrkmrs + T3plorgrs + T3orgmars + T3monirs
  T3wrkmrs ~~ T3plorgrs + T3orgmars + T3monirs
  T3plorgrs  ~~ T3orgmars + T3monirs
  T3orgmars  ~~ T3monirs

  T12initirs ~~ T12wrkmrs + T12plorgrs + T12orgmars + T12monirs
  T12wrkmrs ~~ T12plorgrs + T12orgmars + T12monirs
  T12plorgrs  ~~ T12orgmars + T12monirs
  T12orgmars  ~~ T12monirs

  T14initirs ~~ T14wrkmrs + T14plorgrs + T14orgmars + T14monirs
  T14wrkmrs ~~ T14plorgrs + T14orgmars + T14monirs
  T14plorgrs  ~~ T14orgmars + T14monirs
  T14orgmars  ~~ T14monirs

# latent variable intercepts[means]; fixing the mean of latent variable to be 0, differences will be pushed up into slope 
  MIT3 ~ 0*1
  MIT12 ~ 0*1
  MIT14 ~ 0*1
  MIT14~~ 0*MIT14

## model constraints for effect coding; intercept will be the starting value for variables in the same metric (of the original data). 
  ## indicator loadings must average to 1
    L1 == 5 - L2 - L3 - L4 - L5
  ## indicator means must average to 0 
    t1 == 0 - t2 - t3 - t4 - t5
  
    i =~ 1*MIT3 + 1*MIT12 + 1*MIT14 
    s =~ 0*MIT3 + 1*MIT12 + 2*MIT14'

fit.sec.order <- growth(sec.order, data=PDS_stats, missing= "ML")
summary(fit.sec.order, fit.measures=TRUE, standardized=TRUE)
  # RMSEA= 0.139, SRMR: 0.144, CFI = 0.819, TLI= 0.744, suggesting poor fit (might be because we're modeling too many parameters that aren't significant)
inspect(fit.sec.order, "theta")
semPaths(fit.sec.order, what = "paths", whatLabels= "est", layout = "tree")
  # Loadings (z value and std.all) for latent variables look good
  # Intercepts: Average MI starts at 14.447 and decreases -0.613 across wave (significant!); EF symptom deficits reduce over time
```


12) Fit a series of multiple group models. Constrain some parameters and compare the fit.
```{r setup, include=FALSE}
group1 <- 'MIT3 =~ T3initirs + T3wrkmrs + T3plorgrs +T3orgmars + T3monirs
BRIT3 =~ T3inhibrs + T3shftrs + T3emcnrs 

  MIT3 ~~ 1*MIT3
  BRIT3 ~~ 1*BRIT3

  MIT3 ~~ BRIT3
'

fit.group.1 <- cfa(group1, data=PDS_stats, missing= "ML", group = "sex")
#### Error in eigen(S, symmetric = TRUE) : infinite or missing values in 'x'
summary(fit.group.1, standardized=TRUE, fit.measures=TRUE)
semPaths(fit.group.1,'est', panelGroups=TRUE)

# Labels to fix different parameters across models 
group2 <- 'MIT3 =~ c(L1,L1)*M1 + c(L2,L2)*M2 + c(L3,L3)*M3 + c(L4,L4)*M4 + c(L5,L5)*M5
BRIT3 =~ T3inhibrs + T3shftrs + T3emcnrs 

MIT3 ~~ 1*MIT3
BRIT3 ~~ 1*BRIT3

MIT3 ~~ BRIT3
'

fit.group.2 <- cfa(group2, data=PDS_stats, std.lv=TRUE, group = "sex")
summary(fit.group.2, standardized=TRUE, fit.measures=TRUE)

# comparing models to determine whether constraining groups makes fit worse
anova(fit.group.1,fit.group.2)
```





