---
title: "Presentation"
author: "Kat Lopez"
date: "November 5, 2017"
output: html_document
---

```{r, echo=FALSE, message=F, warning=F, error=F, include=FALSE}
PDS_stats= read.csv("~/Dropbox/3rd Fall/Longitudinal data analysis/STATS_resting_state_BRIEF.csv")
#this converts variables to numeric starting from column 4
id <- c(1,4:ncol(PDS_stats))
PDS_stats[,id] <- as.numeric(as.character(unlist(PDS_stats[,id])))
library(lavaan)
library(semTools)
library(semPlot)
library(lme4)
library(tidyr)

#convert variables
PDS_stats$T3gecrs_combined_conv=PDS_stats$T3gecrs_Combined/100
PDS_stats$T12gecrs_conv=PDS_stats$T12gecrs/100
PDS_stats$T14gecrs_conv=PDS_stats$T14gecrs/100
```



```{r, echo=TRUE, warning=F, error=F}
# Univariate Growth Models
# Global Executive Composite raw scores
# with intercept only 
  Intercept.only= ' i=~ 1*T3gecrs_combined_conv + 1*T12gecrs_conv + 1*T14gecrs_conv' 
  Intercept.only.fit= growth(Intercept.only, data = PDS_stats, missing= "ML")
  summary (Intercept.only.fit, fit.measures=TRUE, standardized=TRUE)
  semPaths(Intercept.only.fit, what = "paths", whatLabels= "est", layout = "tree")
  # RMSEA= 0.022; SRMR= 0.060, both indicating acceptable fit
  # CFI= 0.995; TLI= 0.996, both indicating large distance from the worse fit. 
  

# with a fixed slope
  fixed.slope= ' i=~ 1*T3gecrs_combined_conv + 1*T12gecrs_conv + 1*T14gecrs_conv
  s=~ 0*T3gecrs_combined_conv + 1*T12gecrs_conv + 2*T14gecrs_conv
  s ~~ 0*s'  #fixes slope
  fixed.slope.fit= growth(fixed.slope, data = PDS_stats, missing= "ML")
  inspect(fixed.slope.fit, "cov.lv")
  summary (fixed.slope.fit, fit.measures=TRUE, standardized=TRUE)
  semPaths(fixed.slope.fit, what = "paths", whatLabels= "est", layout = "tree")

  # RMSEA= 0.000; SRMR= 0.031, both indicating better fits.
  # CFI= 1.000; TLI= 1.007, both indicating larger distance from the worse fit.

    
# with a random slope

  random.slope= ' i=~ 1*T3gecrs_combined_conv + 1*T12gecrs_conv + 1*T14gecrs_conv
  s=~ -1*T3gecrs_combined_conv + 0*T12gecrs_conv + 1*T14gecrs_conv'
  random.slope.fit= growth(random.slope, data = PDS_stats, missing= "ML")
  summary (random.slope.fit, fit.measures=TRUE, standardized=TRUE)
  semPaths(random.slope.fit, what = "paths", whatLabels= "est", layout = "tree")
  # RMSEA= 0.000,SRMR= 0.012, similar fit to fixed slope model
  # CFI= 1.000, TFI= 1.014, similar fit to fixed slope model
    

# compare models 
  anova(Intercept.only.fit, fixed.slope.fit) # Intercept only model better fits the data than having a fixed slope (ASK JOSH IF THIS MAKES SENSE)
  anova(fixed.slope.fit, random.slope.fit) # Fixed slope model better fits the data than the random slope model (ASK JOSH IF THIS MAKES SENSE)
  
  
  
### Network connectivity netween Frontoparietal & Cingulo-opercular Network 

  # with intercept only 
  Intercept.only.network= ' i=~ 1*WAVE1_FPN_CON + 1*WAVE2_FPN_CON + 1*WAVE3_FPN_CON' 
  Intercept.only.network.fit= growth(Intercept.only.network, data = PDS_stats, missing= "ML")
  summary (Intercept.only.network.fit, fit.measures=TRUE, standardized=TRUE)
  semPaths(Intercept.only.network.fit, what = "paths", whatLabels= "est", layout = "tree")
  # RMSEA= 0.000; SRMR= 0.037, both suggesting acceptable fits
  # CFI= 1.000; TFI= 1.112, suggesting larger distance from the worse fit (null)
  


# with a fixed slope
  fixed.slope.network= ' i=~ 1*WAVE1_FPN_CON + 1*WAVE2_FPN_CON + 1*WAVE3_FPN_CON
  s=~ 0*WAVE1_FPN_CON + 1*WAVE2_FPN_CON + 2*WAVE3_FPN_CON
  s ~~ 0*s'  #fixes slope
  fixed.slope.network.fit= growth(fixed.slope.network, data = PDS_stats, missing= "ML")
  inspect(fixed.slope.network.fit, "cov.lv")
  summary (fixed.slope.network.fit, fit.measures=TRUE, standardized=TRUE)
  semPaths(fixed.slope.network.fit, what = "paths", whatLabels= "est", layout = "tree")
  # RMSEA= 0.000; SRMR= 0.021, both suggesting acceptable fits
  # CFI= 1.000; TFI= 1.130, suggesting larger distance from the worse fit (null), larger distance than intercept only
  

# with a random slope
  random.slope.network= ' i=~ 1*WAVE1_FPN_CON + 1*WAVE2_FPN_CON + 1*WAVE3_FPN_CON
  s=~ -1*WAVE1_FPN_CON + 0*WAVE2_FPN_CON + 1*WAVE3_FPN_CON'
  random.slope.network.fit= growth(random.slope.network, data = PDS_stats, missing= "ML")
  summary (random.slope.network.fit, fit.measures=TRUE, standardized=TRUE)
  semPaths(random.slope.network.fit, what = "paths", whatLabels= "est", layout = "tree")
  # RMSEA= 0.000; SRMR= 0.019, suggesting acceptable fits
  # CFI= 1.000; TFI= 1.079, suggesting larger distance from the worse fit (null), although slightly smaller distance than fixed slope
  
# compare models 
  anova(Intercept.only.network.fit, fixed.slope.network.fit) # Intercept only model better fits the data than having a fixed slope, although not by much (ASK JOSH IF THIS MAKES SENSE)
  anova(fixed.slope.network.fit, random.slope.network.fit) # Fixed slope model better fits the data than the random slope model (ASK JOSH IF THIS MAKES SENSE)
  
# Bivariate Growth Models
  model.network.bi <- '
  #create global composite EF growth model
      i.p =~ 1*T3gecrs_combined_conv + 1*T12gecrs_conv + 1*T14gecrs_conv 
      s.p =~ 0*T3gecrs_combined_conv + 1*T12gecrs_conv + 2*T14gecrs_conv 
  
  #create between network connectivity growth model 
      i.n =~ 1*WAVE1_FPN_CON + 1*WAVE2_FPN_CON + 1*WAVE3_FPN_CON 
      s.n =~ 0*WAVE1_FPN_CON + 1*WAVE2_FPN_CON + 2*WAVE3_FPN_CON'
  
  fit.network.bi <- growth(model.network.bi, data = PDS_stats, missing= "ML")
  summary(fit.network.bi, fit.measures=TRUE, standardized=TRUE)
  semPaths(fit.network.bi, what = "paths", whatLabels= "est", layout = "tree")
  # RMSEA= 0.000; SRMR=0.040,  suggesting acceptable fits for bivariate growth model
  # CFI= 1.000 ; TLI= 1.022, suggesting larger distance from the worse fit (null), although slightly smaller distance than fixed slope
  
```


```{r, echo=TRUE, warning=F, error=F}

# Metacognition Index of executive function (MI): initiate, working memory, plan/organize, organization of material, & monitor

# RMSEA or SRMR; Above .10 poor fit Below .08 acceptable
# CFI, TFI; Usually >.9 is okay. Some care about > .95

# First wave (T3)
  metacognition.index.T3= ' metacognition.index.T3 =~ T3initirs + T3wrkmrs + T3plorgrs +T3orgmars + T3monirs' 
  fit= cfa(metacognition.index.T3, data= PDS_stats, missing= "ML")
  summary(fit, fit.measures=TRUE, standardized=TRUE)
  # RMSEA= 0.133 #suggests poor fit; SRMR=0.026 # suggests acceptable fit (?- ASK JOSH)
  # CFI= 0.977 ; TLI= 0.955, suggesting larger distance from the worse fit (null)- good thing
  
# Second wave (T12)
  metacognition.index.T12= ' metacognition.index.T12 =~ T12initirs + T12wrkmrs + T12plorgrs +T12orgmars + T12monirs' 
  fit2= cfa(metacognition.index.T12, data= PDS_stats, missing= "ML")
  summary(fit2, fit.measures=TRUE, standardized=TRUE)
  # RMSEA= 0.058; SRMR=0.016 # both suggests acceptable fit 
  # CFI= 0.996 ; TLI= 0.991, suggesting larger distance from the worse fit (null)- good thing
  
# Third wave (T14)
  metacognition.index.T14= ' metacognition.index.T14 =~ T14initirs + T14wrkmrs + T14plorgrs +T14orgmars + T14monirs'
  fit3= cfa(metacognition.index.T14, data= PDS_stats, missing= "ML")
  summary(fit3, fit.measures=TRUE, standardized=TRUE)
  # RMSEA= 0.113 #suggests poor fit; SRMR=0.022 # suggests acceptable fit (?- ASK JOSH)
  # CFI= 0.983 ; TLI= 0.967, suggesting larger distance from the worse fit (null)- good thing
  
# Second Order Growth Model
sec.order <- '
# define latent variables; MI for each waves 1,2,3
  MIT3 =~ NA*T3initirs + L1*T3initirs + L2*T3wrkmrs + L3*T3plorgrs + L4*T3orgmars + L5*T3monirs
  MIT12 =~ NA*T12initirs + L1*T12initirs + L2*T12wrkmrs + L3*T12plorgrs + L4*T12orgmars + L5*T12monirs
  MIT14=~ NA*T14initirs + L1*T14initirs + L2*T14wrkmrs + L3*T14plorgrs + L4*T14orgmars + L5*T14monirs

# intercepts for each indicator
  T3initirs ~ t1*1
  T3wrkmrs ~ t2*1
  T3plorgrs ~ t3*1
  T3orgmars ~ t4*1
  T3monirs ~ t5*1

  T12initirs ~ t1*1
  T12wrkmrs ~ t2*1
  T12plorgrs ~ t3*1
  T12orgmars ~ t4*1
  T12monirs ~ t5*1

  T14initirs ~ t1*1
  T14wrkmrs ~ t2*1
  T14plorgrs ~ t3*1
  T14orgmars ~ t4*1
  T14monirs ~ t5*1

# correlated residuals across time
  T3initirs ~~ T3wrkmrs + T3plorgrs + T3orgmars + T3monirs
  T3wrkmrs ~~ T3plorgrs + T3orgmars + T3monirs
  T3plorgrs  ~~ T3orgmars + T3monirs
  T3orgmars  ~~ T3monirs

  T12initirs ~~ T12wrkmrs + T12plorgrs + T12orgmars + T12monirs
  T12wrkmrs ~~ T12plorgrs + T12orgmars + T12monirs
  T12plorgrs  ~~ T12orgmars + T12monirs
  T12orgmars  ~~ T12monirs

  T14initirs ~~ T14wrkmrs + T14plorgrs + T14orgmars + T14monirs
  T14wrkmrs ~~ T14plorgrs + T14orgmars + T14monirs
  T14plorgrs  ~~ T14orgmars + T14monirs
  T14orgmars  ~~ T14monirs

# latent variable intercepts
  MIT3 ~ 0*1
  MIT12 ~ 0*1
  MIT14 ~ 0*1

# model constraints for effect coding
## loadings must average to 1
  L1 == 5 - L2 - L3 - L4 - L5
## means must average to 0
  t1 == 0 - t2 - t3 - t4 - t5

  i =~ 1*MIT3 + 1*MIT12 + 1*MIT14 
  s =~ 0*MIT3 + 1*MIT12 + 2*MIT14'

fit.sec.order <- growth(sec.order, data=PDS_stats, missing= "ML")
summary(fit.sec.order, fit.measures=TRUE, standardized=TRUE)
inspect(fit.sec.order, "theta") #shows correlation matrix with lots of zeros?
semPaths(fit.sec.order, what = "paths", whatLabels= "est", layout = "tree")
```

